// This file is automatically generated. Do not edit it directly.
// Try to load `@supabase/supabase-js` at runtime; fall back if not installed.
import type { Database } from './types';
declare const require: any;
let createClient: any;
try {
  // eslint-disable-next-line @typescript-eslint/no-var-requires
  createClient = require('@supabase/supabase-js').createClient;
} catch (e) {
  createClient = undefined;
}

function createSupabaseClient() {
  // Use import.meta.env for client-side (Vite build-time replacement)
  // Fall back to process.env for SSR (server-side rendering)
  const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || process.env.SUPABASE_URL;
  const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || process.env.SUPABASE_PUBLISHABLE_KEY;

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ['VITE_SUPABASE_URL / SUPABASE_URL'] : []),
      ...(!SUPABASE_PUBLISHABLE_KEY ? ['VITE_SUPABASE_PUBLISHABLE_KEY / SUPABASE_PUBLISHABLE_KEY'] : []),
    ];
    const message = `Missing Supabase environment variable(s): ${missing.join(', ')}. Set them in Vercel project settings.`;
    console.error(`[Supabase] ${message}`);

    const queryFallback = {
      select() {
        return this;
      },
      eq() {
        return this;
      },
      order() {
        return this;
      },
      limit() {
        return this;
      },
      single() {
        return this;
      },
      then(resolve: (value: any) => any) {
        return resolve({ data: null, error: new Error(message) });
      },
      catch() {
        return this;
      },
    };

    const fallback: any = {
      auth: {
        getSession: async () => ({ data: { session: null }, error: null }),
        signInWithPassword: async () => ({ data: null, error: new Error(message) }),
        signUp: async () => ({ data: null, error: new Error(message) }),
        getUser: async () => ({ data: { user: null }, error: null }),
      },
      from: () => queryFallback,
    };

    return fallback as ReturnType<typeof createSupabaseClient>;
  }

  if (!createClient) {
    // If the runtime package is missing, return the fallback defined below.
    const message = `Supabase client package not installed.`;
    console.error(`[Supabase] ${message}`);
    return fallback as ReturnType<typeof createSupabaseClient>;
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: typeof window !== 'undefined' ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    }
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});

