// This file is automatically generated. Do not edit it directly.
// Server-side Supabase client with service role key - bypasses RLS.
// Use this for admin operations in server functions and server routes only.
// For user-authenticated queries (with RLS), use the auth middleware instead.
// Try to load `@supabase/supabase-js` at runtime; fall back if not installed.
declare const require: any;
let createClient: any;
try {
  // eslint-disable-next-line @typescript-eslint/no-var-requires
  createClient = require('@supabase/supabase-js').createClient;
} catch (e) {
  createClient = undefined;
}
import type { Database } from './types';

function createSupabaseAdminClient() {
  const SUPABASE_URL = process.env.SUPABASE_URL;
  const SUPABASE_SERVICE_ROLE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY;

  if (!SUPABASE_URL || !SUPABASE_SERVICE_ROLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ['SUPABASE_URL'] : []),
      ...(!SUPABASE_SERVICE_ROLE_KEY ? ['SUPABASE_SERVICE_ROLE_KEY'] : []),
    ];
    const message = `Missing Supabase environment variable(s): ${missing.join(', ')}. Connect Supabase in Lovable Cloud.`;
    console.error(`[Supabase] ${message}`);
    // Instead of throwing, return a safe fallback client so the app can run without Supabase.
    const queryFallback = {
      select() { return this; },
      eq() { return this; },
      order() { return this; },
      limit() { return this; },
      single() { return this; },
      then(resolve: (value: any) => any) { return resolve({ data: null, error: new Error(message) }); },
      catch() { return this; },
    };

    const fallback: any = {
      auth: {
        getSession: async () => ({ data: { session: null }, error: null }),
        signInWithPassword: async () => ({ data: null, error: new Error(message) }),
        signUp: async () => ({ data: null, error: new Error(message) }),
        getUser: async () => ({ data: { user: null }, error: null }),
      },
      from: () => queryFallback,
      rpc: () => ({ then: (resolve: any) => resolve({ data: null, error: new Error(message) }) }),
    };

    return fallback as ReturnType<typeof createSupabaseAdminClient>;
  }

  if (!createClient) {
    const message = `Supabase client package not installed.`;
    console.error(`[Supabase] ${message}`);
    // Return a fallback that throws safe errors when used
    const queryFallback = {
      select() { return this; },
      eq() { return this; },
      order() { return this; },
      limit() { return this; },
      single() { return this; },
      then(resolve: (value: any) => any) { return resolve({ data: null, error: new Error(message) }); },
      catch() { return this; },
    };
    const fallback: any = {
      auth: {
        getSession: async () => ({ data: { session: null }, error: null }),
        signInWithPassword: async () => ({ data: null, error: new Error(message) }),
        signUp: async () => ({ data: null, error: new Error(message) }),
        getUser: async () => ({ data: { user: null }, error: null }),
      },
      from: () => queryFallback,
      rpc: () => ({ then: (resolve: any) => resolve({ data: null, error: new Error(message) }) }),
    };
    return fallback as ReturnType<typeof createSupabaseAdminClient>;
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY, {
    auth: {
      storage: undefined,
      persistSession: false,
      autoRefreshToken: false,
    }
  });
}

let _supabaseAdmin: ReturnType<typeof createSupabaseAdminClient> | undefined;

// Server-side Supabase client with service role - bypasses RLS
// SECURITY: Only use this for trusted server-side operations, never expose to client code
// Load inside server handlers: const { supabaseAdmin } = await import("@/integrations/supabase/client.server");
// Top-level import is safe only in other .server.ts modules - route files and *.functions.ts ship to the client bundle.
export const supabaseAdmin = new Proxy({} as ReturnType<typeof createSupabaseAdminClient>, {
  get(_, prop, receiver) {
    if (!_supabaseAdmin) _supabaseAdmin = createSupabaseAdminClient();
    return Reflect.get(_supabaseAdmin, prop, receiver);
  },
});
